/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.saurabh.spring;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

@Component//non qualified and decaptaiblize id - samsung
public class Samsung {
	@Autowired
	@Qualifier("snapDragon")
	MobileProcessor cpu;
	
   public MobileProcessor getCpu() {
		return cpu;
	}

	public void setCpu(MobileProcessor cpu) {
		this.cpu = cpu;
	}

public void config()
   {
	   System.out.println("OCta core 4");
	   cpu.process();
   }
}
